name: dance
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^7.4.0 # Router

  provider: ^6.0.3 # Dependency Injection
  path_provider: ^2.0.11
  equatable: ^2.0.3

  bloc: ^8.0.3 # Bloc Pattern Business Logic
  flutter_bloc: ^8.0.1 # Bloc Pattern Presentation Logic

  shared_preferences: ^2.0.15 # Storage
  path: ^1.8.3 # Path
  intl: ^0.18.0 # Translations
  share_plus: ^7.0.2

  youtube_player_flutter: ^8.1.2
  easy_refresh: ^3.3.0+1
  duration_picker: ^1.1.1 # Duration picker for form

  material_design_icons_flutter: ^7.0.7296 # Material Design Icons
  cupertino_icons: ^1.0.5 # Cupertino Icons
  settings_ui: ^2.0.2

  # Database libs

  sqlite3_flutter_libs: ^0.5.17 # Dart binding for SQLite3 (iOS/Android/MacOS/Linux/Windows)
  sqflite: ^2.3.0 # SQLite3 lib for iOS/Android/MacOS
  sqflite_common_ffi: ^2.3.0+2 # SQLite3 lib for Linux/Windows/DartVM
  # TODO: Add SQLite flutter web
  # sqflite_common_ffi_web: ^0.4.0 # SQLite3 lib for Web

  json_annotation: ^4.6.0 # JSON serialization
  uuid: ^3.0.6

  quiver: ^3.1.0

dev_dependencies:
  build_runner: ^2.1.11
  build_verify: ^3.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  auto_route_generator: ^7.1.1 # Generator for auto_route
  json_serializable: ^6.3.1 # Generator for json_annotation


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true

dependency_overrides:
  duration_picker:
    git: https://github.com/juliansteenbakker/duration_picker.git
